CREATE ROLE dev_sec_ops_role;

GRANT USAGE ON DATABASE health_app TO ROLE dev_sec_ops_role;
GRANT CREATE SCHEMA ON DATABASE health_app TO ROLE dev_sec_ops_role;
GRANT USAGE ON SCHEMA RAW TO ROLE dev_sec_ops_role;
GRANT USAGE ON SCHEMA STAGING TO ROLE dev_sec_ops_role;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dev_sec_ops_role;



GRANT CREATE DATABASE, CREATE USER, CREATE ROLE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE dev_sec_ops_role WITH GRANT OPTION;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE dev_sec_ops_role WITH GRANT OPTIONS;