CREATE OR REPLACE STORAGE INTEGRATION s3_health_app
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS=('s3://adahealthapp')
STORAGE_AWS_ROLE_ARN='arn:aws:iam::970547375655:role/role_acces_snowflake';

CREATE OR ALTER STAGE raw.s3_stage
FILE_FORMAT = raw.csv_file
URL='s3://adahealthapp'
STORAGE_INTEGRATION = s3_health_app
;