CREATE DATABASE HEALTH_APP_2;
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;

CREATE ROLE devops_role;

GRANT ROLE devops_role TO USER deployment_user;

GRANT USAGE ON DATABASE HEALTH_APP_2 TO ROLE DEVOPS_ROLE;
GRANT ALL ON SCHEMA raw TO ROLE devops_role;
GRANT ALL ON SCHEMA staging TO ROLE devops_role;

CREATE ROLE application_role;
GRANT ROLE application_role TO USER deployment_user;

CREATE ROLE engineer_role;

